### ISSUE TITLE
RequestBin destination is not created.

### ISSUE THREAD

**Issue by ashish211981** [streamsets/tutorials#17] opened 2016-08-03 10:24 UTC
Despite building the projects and copied the jar file to desired location custom requestbin not created.

**Comment by metadaddy** [comment] 2016-08-11 00:44
Did you create a new RequestBin at the website: http://requestb.in?

**Comment by metadaddy** [comment] 2016-10-25 00:50
Closing this since I haven't had a reply. Feel free to reopen if you're still having a problem, @ashish211981

**Comment by metadaddy** [comment] 2016-12-09 04:47
Closing, since it's not clear what the problem is. Feel free to reopen, @ashish211981, if you want to provide some more detail.

**Closed by metadaddy** 2016-12-09 04:47 UTC
